#!/bin/sh
set -eu

ROOT=$(CDPATH= cd -- "$(dirname -- "$0")/.." && pwd)
SDK=$(xcrun --sdk macosx --show-sdk-path)
SDK_VERSION=$(xcrun --sdk macosx --show-sdk-version)
CC=$(xcrun --sdk macosx --find clang)
COMPILER_VERSION=$($CC --version)
COMPILER_VERSION=${COMPILER_VERSION%%"
"*}

mkdir -p "$ROOT/bin" "$ROOT/artifacts"

COMMON_FLAGS="-std=c17 -O2 -Wall -Wextra -Werror -arch arm64 -isysroot $SDK -mmacosx-version-min=15.0"
LINK_FLAGS="-Wl,-pie -Wl,-dead_strip -Wl,-no_uuid"

# shellcheck disable=SC2086
"$CC" $COMMON_FLAGS $LINK_FLAGS \
  "$ROOT/src/prompt_history_common.c" \
  "$ROOT/src/prompt_history_helper.c" \
  -lsqlite3 \
  -o "$ROOT/bin/prompt-history-helper"
chmod 0755 "$ROOT/bin/prompt-history-helper"

set -- $(/usr/bin/shasum -a 256 "$ROOT/bin/prompt-history-helper")
HELPER_SHA=$1

cat > "$ROOT/src/prompt_history_generated_artifact.h" <<EOF
#ifndef PROMPT_HISTORY_GENERATED_ARTIFACT_H
#define PROMPT_HISTORY_GENERATED_ARTIFACT_H
#define PH_HELPER_PROTOCOL 1
#define PH_EXPECTED_HELPER_SHA256 "$HELPER_SHA"
#endif
EOF

cat > "$ROOT/hooks/artifact.ts" <<EOF
// Generated by scripts/build-artifacts.sh. Do not edit.
export const HELPER_PROTOCOL = 1
export const EXPECTED_HELPER_SHA256 = '$HELPER_SHA'
EOF

# shellcheck disable=SC2086
"$CC" $COMMON_FLAGS $LINK_FLAGS \
  "$ROOT/src/prompt_history_common.c" \
  "$ROOT/src/prompt_history_bridge.c" \
  -o "$ROOT/bin/prompt-history-bridge"
chmod 0755 "$ROOT/bin/prompt-history-bridge"

set -- $(/usr/bin/shasum -a 256 "$ROOT/bin/prompt-history-bridge")
BRIDGE_SHA=$1
set -- $(/usr/bin/shasum -a 256 "$ROOT/src/prompt_history_common.c")
COMMON_SOURCE_SHA=$1
set -- $(/usr/bin/shasum -a 256 "$ROOT/src/prompt_history_helper.c")
HELPER_SOURCE_SHA=$1
set -- $(/usr/bin/shasum -a 256 "$ROOT/src/prompt_history_bridge.c")
BRIDGE_SOURCE_SHA=$1
set -- $(/usr/bin/shasum -a 256 "$ROOT/src/prompt_history_generated_artifact.h")
GENERATED_HEADER_SHA=$1
set -- $(/usr/bin/shasum -a 256 "$ROOT/scripts/build-artifacts.sh")
BUILD_SCRIPT_SHA=$1

cat > "$ROOT/artifacts/helper-manifest.json" <<EOF
{
  "formatVersion": 1,
  "target": "darwin-arm64-macos15",
  "file": "bin/prompt-history-helper",
  "sha256": "$HELPER_SHA",
  "bridgeFile": "bin/prompt-history-bridge",
  "bridgeSha256": "$BRIDGE_SHA",
  "helperProtocol": 1,
  "schemaReadMin": 1,
  "schemaReadMax": 2,
  "schemaWriteMin": 2,
  "schemaWriteMax": 2,
  "schemaMigrations": ["1->2"],
  "sqliteMinimumVersionNumber": 3035000,
  "sqliteRequiredCapability": "UPDATE RETURNING",
  "compiler": "$COMPILER_VERSION",
  "sdkVersion": "$SDK_VERSION",
  "linker": "ld64 through Apple clang",
  "source": "src/prompt_history_helper.c",
  "sourceSha256": "$HELPER_SOURCE_SHA",
  "bridgeSource": "src/prompt_history_bridge.c",
  "bridgeSourceSha256": "$BRIDGE_SOURCE_SHA",
  "commonSource": "src/prompt_history_common.c",
  "commonSourceSha256": "$COMMON_SOURCE_SHA",
  "generatedHeader": "src/prompt_history_generated_artifact.h",
  "generatedHeaderSha256": "$GENERATED_HEADER_SHA",
  "buildCommand": "scripts/build-artifacts.sh",
  "buildScriptSha256": "$BUILD_SCRIPT_SHA",
  "allowedDynamicDependencies": [
    "/usr/lib/libSystem.B.dylib",
    "/usr/lib/libsqlite3.dylib"
  ]
}
EOF
